import { db } from "./db";
import { serviceCategories } from "@shared/schema";

// Top 100 Service Categories based on TaskRabbit, Thumbtack, Handy research
export const SERVICE_CATEGORIES = [
  // 🏠 HOME MAINTENANCE & REPAIRS (20 categories)
  {
    name: "General Handyman",
    nameAr: "العمال المهرة العامة",
    nameFr: "Bricoleur Général",
    description: "General repairs and maintenance around the house",
    descriptionAr: "الإصلاحات العامة والصيانة في المنزل",
    descriptionFr: "Réparations générales et maintenance de la maison",
    icon: "Wrench",
    color: "bg-blue-500",
    category: "home_maintenance",
    isPopular: true,
    sortOrder: 1,
    averagePrice: "25.00",
    estimatedDuration: "2-4 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Plumbing Services",
    nameAr: "خدمات السباكة",
    nameFr: "Services de Plomberie",
    description: "Faucet, toilet, sink repairs and installations",
    descriptionAr: "إصلاح وتركيب الحنفيات والمراحيض والأحواض",
    descriptionFr: "Réparations et installations de robinets, toilettes, éviers",
    icon: "Droplets",
    color: "bg-cyan-500",
    category: "home_maintenance",
    isPopular: true,
    sortOrder: 2,
    averagePrice: "35.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "expert",
    requiresLicense: true
  },
  {
    name: "Electrical Services",
    nameAr: "الخدمات الكهربائية",
    nameFr: "Services Électriques",
    description: "Outlet installation, light fixtures, electrical repairs",
    descriptionAr: "تركيب المقابس وتركيبات الإضاءة والإصلاحات الكهربائية",
    descriptionFr: "Installation de prises, luminaires, réparations électriques",
    icon: "Zap",
    color: "bg-yellow-500",
    category: "home_maintenance",
    isPopular: true,
    sortOrder: 3,
    averagePrice: "40.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "expert",
    requiresLicense: true,
    emergencyService: true
  },
  {
    name: "HVAC Services",
    nameAr: "خدمات التدفئة والتهوية وتكييف الهواء",
    nameFr: "Services CVC",
    description: "Heating, ventilation, and air conditioning services",
    descriptionAr: "خدمات التدفئة والتهوية وتكييف الهواء",
    descriptionFr: "Services de chauffage, ventilation et climatisation",
    icon: "Wind",
    color: "bg-teal-500",
    category: "home_maintenance",
    sortOrder: 4,
    averagePrice: "45.00",
    estimatedDuration: "2-6 hours",
    skillLevel: "expert",
    requiresLicense: true
  },
  {
    name: "Appliance Repair",
    nameAr: "إصلاح الأجهزة",
    nameFr: "Réparation d'Appareils",
    description: "Washing machine, dryer, dishwasher, refrigerator repair",
    descriptionAr: "إصلاح الغسالة والمجفف وغسالة الصحون والثلاجة",
    descriptionFr: "Réparation de lave-linge, sèche-linge, lave-vaisselle, réfrigérateur",
    icon: "Refrigerator",
    color: "bg-gray-500",
    category: "home_maintenance",
    sortOrder: 5,
    averagePrice: "50.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "expert"
  },
  {
    name: "Drywall Repair",
    nameAr: "إصلاح الجدران الجافة",
    nameFr: "Réparation de Cloisons Sèches",
    description: "Hole patching, crack repair, wall restoration",
    descriptionAr: "ترقيع الثقوب وإصلاح الشقوق واستعادة الجدران",
    descriptionFr: "Colmatage de trous, réparation de fissures, restauration de murs",
    icon: "Square",
    color: "bg-stone-500",
    category: "home_maintenance",
    sortOrder: 6,
    averagePrice: "30.00",
    estimatedDuration: "2-4 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Door & Window Services",
    nameAr: "خدمات الأبواب والنوافذ",
    nameFr: "Services Portes et Fenêtres",
    description: "Installation, repair, and adjustment of doors and windows",
    descriptionAr: "تركيب وإصلاح وتعديل الأبواب والنوافذ",
    descriptionFr: "Installation, réparation et ajustement de portes et fenêtres",
    icon: "DoorOpen",
    color: "bg-amber-500",
    category: "home_maintenance",
    sortOrder: 7,
    averagePrice: "35.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Flooring Installation",
    nameAr: "تركيب الأرضيات",
    nameFr: "Installation de Revêtements de Sol",
    description: "Hardwood, laminate, tile, carpet installation",
    descriptionAr: "تركيب الخشب الصلب والصفائح والبلاط والسجاد",
    descriptionFr: "Installation de parquet, stratifié, carrelage, moquette",
    icon: "Square",
    color: "bg-orange-500",
    category: "home_maintenance",
    sortOrder: 8,
    averagePrice: "40.00",
    estimatedDuration: "4-8 hours",
    skillLevel: "expert"
  },
  {
    name: "Roofing Services",
    nameAr: "خدمات الأسقف",
    nameFr: "Services de Toiture",
    description: "Roof repair, maintenance, and installation",
    descriptionAr: "إصلاح وصيانة وتركيب الأسقف",
    descriptionFr: "Réparation, maintenance et installation de toiture",
    icon: "Home",
    color: "bg-red-500",
    category: "home_maintenance",
    sortOrder: 9,
    averagePrice: "55.00",
    estimatedDuration: "4-8 hours",
    skillLevel: "expert",
    requiresLicense: true
  },
  {
    name: "Gutter Services",
    nameAr: "خدمات المزاريب",
    nameFr: "Services de Gouttières",
    description: "Gutter cleaning, repair, and installation",
    descriptionAr: "تنظيف وإصلاح وتركيب المزاريب",
    descriptionFr: "Nettoyage, réparation et installation de gouttières",
    icon: "Waves",
    color: "bg-blue-600",
    category: "home_maintenance",
    sortOrder: 10,
    averagePrice: "35.00",
    estimatedDuration: "2-4 hours",
    skillLevel: "intermediate"
  },

  // 🧹 CLEANING SERVICES (15 categories)
  {
    name: "House Cleaning",
    nameAr: "تنظيف المنزل",
    nameFr: "Nettoyage de Maison",
    description: "Regular house cleaning and deep cleaning services",
    descriptionAr: "خدمات تنظيف المنزل العادية والعميقة",
    descriptionFr: "Services de nettoyage de maison régulier et en profondeur",
    icon: "Sparkles",
    color: "bg-purple-500",
    category: "cleaning",
    isPopular: true,
    sortOrder: 11,
    averagePrice: "30.00",
    estimatedDuration: "2-4 hours",
    skillLevel: "beginner"
  },
  {
    name: "Office Cleaning",
    nameAr: "تنظيف المكاتب",
    nameFr: "Nettoyage de Bureau",
    description: "Commercial and office space cleaning",
    descriptionAr: "تنظيف المساحات التجارية والمكتبية",
    descriptionFr: "Nettoyage d'espaces commerciaux et de bureaux",
    icon: "Building2",
    color: "bg-indigo-500",
    category: "cleaning",
    sortOrder: 12,
    averagePrice: "25.00",
    estimatedDuration: "3-6 hours",
    skillLevel: "beginner"
  },
  {
    name: "Carpet Cleaning",
    nameAr: "تنظيف السجاد",
    nameFr: "Nettoyage de Tapis",
    description: "Professional carpet and rug cleaning",
    descriptionAr: "تنظيف السجاد والبسط المهني",
    descriptionFr: "Nettoyage professionnel de tapis et moquettes",
    icon: "Layers",
    color: "bg-pink-500",
    category: "cleaning",
    sortOrder: 13,
    averagePrice: "40.00",
    estimatedDuration: "2-3 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Window Cleaning",
    nameAr: "تنظيف النوافذ",
    nameFr: "Nettoyage de Vitres",
    description: "Interior and exterior window cleaning",
    descriptionAr: "تنظيف النوافذ الداخلية والخارجية",
    descriptionFr: "Nettoyage de vitres intérieures et extérieures",
    icon: "Square",
    color: "bg-sky-500",
    category: "cleaning",
    sortOrder: 14,
    averagePrice: "35.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "beginner"
  },
  {
    name: "Move-in/Move-out Cleaning",
    nameAr: "تنظيف الانتقال",
    nameFr: "Nettoyage de Déménagement",
    description: "Deep cleaning for moving in or out",
    descriptionAr: "التنظيف العميق للانتقال داخل أو خارج",
    descriptionFr: "Nettoyage en profondeur pour emménagement ou déménagement",
    icon: "Package",
    color: "bg-emerald-500",
    category: "cleaning",
    sortOrder: 15,
    averagePrice: "45.00",
    estimatedDuration: "4-6 hours",
    skillLevel: "intermediate"
  },

  // 🎨 PAINTING & DECORATION (10 categories)
  {
    name: "Interior Painting",
    nameAr: "الطلاء الداخلي",
    nameFr: "Peinture Intérieure",
    description: "Interior wall and ceiling painting",
    descriptionAr: "طلاء الجدران والأسقف الداخلية",
    descriptionFr: "Peinture de murs et plafonds intérieurs",
    icon: "Paintbrush",
    color: "bg-violet-500",
    category: "painting",
    isPopular: true,
    sortOrder: 16,
    averagePrice: "35.00",
    estimatedDuration: "4-8 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Exterior Painting",
    nameAr: "الطلاء الخارجي",
    nameFr: "Peinture Extérieure",
    description: "Exterior house and building painting",
    descriptionAr: "طلاء المنزل والمباني الخارجية",
    descriptionFr: "Peinture extérieure de maisons et bâtiments",
    icon: "Home",
    color: "bg-rose-500",
    category: "painting",
    sortOrder: 17,
    averagePrice: "40.00",
    estimatedDuration: "6-12 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Wallpaper Installation",
    nameAr: "تركيب ورق الحائط",
    nameFr: "Pose de Papier Peint",
    description: "Wallpaper installation and removal",
    descriptionAr: "تركيب وإزالة ورق الحائط",
    descriptionFr: "Installation et enlèvement de papier peint",
    icon: "Image",
    color: "bg-fuchsia-500",
    category: "painting",
    sortOrder: 18,
    averagePrice: "30.00",
    estimatedDuration: "3-6 hours",
    skillLevel: "intermediate"
  },

  // 🌿 OUTDOOR & LANDSCAPING (15 categories)
  {
    name: "Lawn Care & Mowing",
    nameAr: "رعاية العشب والجز",
    nameFr: "Entretien de Pelouse",
    description: "Regular lawn mowing and maintenance",
    descriptionAr: "جز العشب العادي والصيانة",
    descriptionFr: "Tonte de pelouse régulière et entretien",
    icon: "Scissors",
    color: "bg-green-500",
    category: "outdoor",
    isPopular: true,
    sortOrder: 19,
    averagePrice: "25.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "beginner"
  },
  {
    name: "Landscaping Design",
    nameAr: "تصميم المناظر الطبيعية",
    nameFr: "Conception Paysagère",
    description: "Garden design and landscaping services",
    descriptionAr: "تصميم الحدائق وخدمات تنسيق المواقع",
    descriptionFr: "Conception de jardins et services d'aménagement paysager",
    icon: "Trees",
    color: "bg-lime-500",
    category: "outdoor",
    sortOrder: 20,
    averagePrice: "50.00",
    estimatedDuration: "4-8 hours",
    skillLevel: "expert"
  },
  {
    name: "Tree Services",
    nameAr: "خدمات الأشجار",
    nameFr: "Services d'Arbres",
    description: "Tree trimming, removal, and maintenance",
    descriptionAr: "تقليم وإزالة وصيانة الأشجار",
    descriptionFr: "Élagage, abattage et entretien d'arbres",
    icon: "TreePine",
    color: "bg-green-600",
    category: "outdoor",
    sortOrder: 21,
    averagePrice: "60.00",
    estimatedDuration: "2-6 hours",
    skillLevel: "expert",
    requiresLicense: true
  },
  {
    name: "Pool Services",
    nameAr: "خدمات المسابح",
    nameFr: "Services de Piscine",
    description: "Pool cleaning, maintenance, and repair",
    descriptionAr: "تنظيف وصيانة وإصلاح المسابح",
    descriptionFr: "Nettoyage, entretien et réparation de piscines",
    icon: "Waves",
    color: "bg-cyan-600",
    category: "outdoor",
    sortOrder: 22,
    averagePrice: "45.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Fence Installation",
    nameAr: "تركيب الأسوار",
    nameFr: "Installation de Clôtures",
    description: "Fence installation and repair services",
    descriptionAr: "خدمات تركيب وإصلاح الأسوار",
    descriptionFr: "Services d'installation et réparation de clôtures",
    icon: "Fence",
    color: "bg-slate-500",
    category: "outdoor",
    sortOrder: 23,
    averagePrice: "40.00",
    estimatedDuration: "4-8 hours",
    skillLevel: "intermediate"
  },

  // 📦 MOVING & DELIVERY (10 categories)
  {
    name: "Furniture Assembly",
    nameAr: "تجميع الأثاث",
    nameFr: "Assemblage de Meubles",
    description: "IKEA and furniture assembly services",
    descriptionAr: "خدمات تجميع أثاث إيكيا والأثاث",
    descriptionFr: "Services d'assemblage de meubles IKEA et autres",
    icon: "Package",
    color: "bg-amber-600",
    category: "moving",
    isPopular: true,
    sortOrder: 24,
    averagePrice: "30.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "beginner"
  },
  {
    name: "Moving Help",
    nameAr: "مساعدة في النقل",
    nameFr: "Aide au Déménagement",
    description: "Heavy lifting, packing, and moving assistance",
    descriptionAr: "رفع الأثقال والتعبئة ومساعدة النقل",
    descriptionFr: "Manutention, emballage et assistance déménagement",
    icon: "Truck",
    color: "bg-orange-600",
    category: "moving",
    isPopular: true,
    sortOrder: 25,
    averagePrice: "35.00",
    estimatedDuration: "2-6 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Delivery Services",
    nameAr: "خدمات التوصيل",
    nameFr: "Services de Livraison",
    description: "Local delivery and courier services",
    descriptionAr: "خدمات التوصيل المحلي والبريد السريع",
    descriptionFr: "Services de livraison locale et de coursier",
    icon: "Package2",
    color: "bg-blue-700",
    category: "moving",
    sortOrder: 26,
    averagePrice: "20.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "beginner"
  },

  // 📺 TECH & ELECTRONICS (12 categories)
  {
    name: "TV Mounting",
    nameAr: "تركيب التلفزيون",
    nameFr: "Montage de Téléviseur",
    description: "TV wall mounting and setup services",
    descriptionAr: "خدمات تركيب التلفزيون على الحائط والإعداد",
    descriptionFr: "Services de montage mural et configuration de téléviseur",
    icon: "Monitor",
    color: "bg-gray-600",
    category: "tech",
    isPopular: true,
    sortOrder: 27,
    averagePrice: "40.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Smart Home Setup",
    nameAr: "إعداد المنزل الذكي",
    nameFr: "Configuration Maison Intelligente",
    description: "Smart home device installation and configuration",
    descriptionAr: "تركيب وتكوين أجهزة المنزل الذكي",
    descriptionFr: "Installation et configuration d'appareils maison intelligente",
    icon: "Smartphone",
    color: "bg-purple-600",
    category: "tech",
    sortOrder: 28,
    averagePrice: "45.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Computer Repair",
    nameAr: "إصلاح الكمبيوتر",
    nameFr: "Réparation d'Ordinateur",
    description: "Computer troubleshooting and repair services",
    descriptionAr: "خدمات استكشاف أخطاء الكمبيوتر وإصلاحها",
    descriptionFr: "Services de dépannage et réparation d'ordinateurs",
    icon: "Laptop",
    color: "bg-slate-600",
    category: "tech",
    sortOrder: 29,
    averagePrice: "50.00",
    estimatedDuration: "1-4 hours",
    skillLevel: "expert"
  },
  {
    name: "Security System Installation",
    nameAr: "تركيب نظام الأمان",
    nameFr: "Installation Système de Sécurité",
    description: "Home security camera and alarm installation",
    descriptionAr: "تركيب كاميرات الأمان المنزلي وأجهزة الإنذار",
    descriptionFr: "Installation de caméras de sécurité et d'alarmes domestiques",
    icon: "Shield",
    color: "bg-red-600",
    category: "tech",
    sortOrder: 30,
    averagePrice: "55.00",
    estimatedDuration: "2-4 hours",
    skillLevel: "expert"
  },

  // 🐕 PET SERVICES (8 categories)
  {
    name: "Dog Walking",
    nameAr: "تمشية الكلاب",
    nameFr: "Promenade de Chiens",
    description: "Daily dog walking and exercise services",
    descriptionAr: "خدمات تمشية وتمرين الكلاب اليومية",
    descriptionFr: "Services quotidiens de promenade et d'exercice pour chiens",
    icon: "Dog",
    color: "bg-yellow-600",
    category: "pets",
    sortOrder: 31,
    averagePrice: "15.00",
    estimatedDuration: "30-60 minutes",
    skillLevel: "beginner"
  },
  {
    name: "Pet Sitting",
    nameAr: "رعاية الحيوانات الأليفة",
    nameFr: "Garde d'Animaux",
    description: "In-home pet care and sitting services",
    descriptionAr: "خدمات رعاية الحيوانات الأليفة في المنزل",
    descriptionFr: "Services de garde d'animaux à domicile",
    icon: "Heart",
    color: "bg-pink-600",
    category: "pets",
    sortOrder: 32,
    averagePrice: "20.00",
    estimatedDuration: "2-8 hours",
    skillLevel: "beginner"
  },
  {
    name: "Pet Grooming",
    nameAr: "تجميل الحيوانات الأليفة",
    nameFr: "Toilettage d'Animaux",
    description: "Professional pet grooming services",
    descriptionAr: "خدمات تجميل الحيوانات الأليفة المهنية",
    descriptionFr: "Services professionnels de toilettage d'animaux",
    icon: "Scissors",
    color: "bg-teal-600",
    category: "pets",
    sortOrder: 33,
    averagePrice: "35.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "intermediate"
  },

  // 🚗 AUTOMOTIVE (5 categories)
  {
    name: "Car Washing",
    nameAr: "غسيل السيارات",
    nameFr: "Lavage de Voiture",
    description: "Mobile car washing and detailing",
    descriptionAr: "غسيل السيارات المتنقل والتفصيل",
    descriptionFr: "Lavage de voiture mobile et détaillage",
    icon: "Car",
    color: "bg-blue-800",
    category: "automotive",
    sortOrder: 34,
    averagePrice: "25.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "beginner"
  },
  {
    name: "Car Repair",
    nameAr: "إصلاح السيارات",
    nameFr: "Réparation Automobile",
    description: "Basic car maintenance and repair services",
    descriptionAr: "خدمات صيانة وإصلاح السيارات الأساسية",
    descriptionFr: "Services de maintenance et réparation automobile de base",
    icon: "Wrench",
    color: "bg-red-700",
    category: "automotive",
    sortOrder: 35,
    averagePrice: "60.00",
    estimatedDuration: "1-4 hours",
    skillLevel: "expert",
    requiresLicense: true
  },

  // 💼 BUSINESS SERVICES (10 categories)
  {
    name: "Data Entry",
    nameAr: "إدخال البيانات",
    nameFr: "Saisie de Données",
    description: "Professional data entry and processing",
    descriptionAr: "إدخال ومعالجة البيانات المهنية",
    descriptionFr: "Saisie et traitement professionnel de données",
    icon: "Database",
    color: "bg-indigo-600",
    category: "business",
    sortOrder: 36,
    averagePrice: "15.00",
    estimatedDuration: "2-6 hours",
    skillLevel: "beginner"
  },
  {
    name: "Virtual Assistant",
    nameAr: "المساعد الافتراضي",
    nameFr: "Assistant Virtuel",
    description: "Administrative and personal assistant services",
    descriptionAr: "خدمات المساعد الإداري والشخصي",
    descriptionFr: "Services d'assistant administratif et personnel",
    icon: "User",
    color: "bg-purple-700",
    category: "business",
    sortOrder: 37,
    averagePrice: "20.00",
    estimatedDuration: "2-8 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Translation Services",
    nameAr: "خدمات الترجمة",
    nameFr: "Services de Traduction",
    description: "Document and content translation",
    descriptionAr: "ترجمة الوثائق والمحتوى",
    descriptionFr: "Traduction de documents et contenu",
    icon: "Languages",
    color: "bg-emerald-600",
    category: "business",
    sortOrder: 38,
    averagePrice: "25.00",
    estimatedDuration: "1-4 hours",
    skillLevel: "expert"
  },

  // 🎓 EDUCATION & TUTORING (8 categories)
  {
    name: "Math Tutoring",
    nameAr: "دروس الرياضيات",
    nameFr: "Cours de Mathématiques",
    description: "Private math tutoring and lessons",
    descriptionAr: "دروس ودروس الرياضيات الخاصة",
    descriptionFr: "Cours particuliers et leçons de mathématiques",
    icon: "Calculator",
    color: "bg-green-700",
    category: "education",
    sortOrder: 39,
    averagePrice: "30.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "expert"
  },
  {
    name: "Language Tutoring",
    nameAr: "دروس اللغة",
    nameFr: "Cours de Langue",
    description: "Language learning and conversation practice",
    descriptionAr: "تعلم اللغة وممارسة المحادثة",
    descriptionFr: "Apprentissage de langues et pratique de conversation",
    icon: "MessageCircle",
    color: "bg-blue-900",
    category: "education",
    sortOrder: 40,
    averagePrice: "25.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "expert"
  },
  {
    name: "Computer Skills Training",
    nameAr: "تدريب مهارات الكمبيوتر",
    nameFr: "Formation Compétences Informatiques",
    description: "Basic computer and software training",
    descriptionAr: "التدريب الأساسي على الكمبيوتر والبرمجيات",
    descriptionFr: "Formation de base en informatique et logiciels",
    icon: "Monitor",
    color: "bg-slate-700",
    category: "education",
    sortOrder: 41,
    averagePrice: "35.00",
    estimatedDuration: "1-3 hours",
    skillLevel: "intermediate"
  },

  // 🎉 EVENTS & PARTY (5 categories)
  {
    name: "Event Planning",
    nameAr: "تخطيط الأحداث",
    nameFr: "Planification d'Événements",
    description: "Party and event planning services",
    descriptionAr: "خدمات تخطيط الحفلات والأحداث",
    descriptionFr: "Services de planification de fêtes et événements",
    icon: "Calendar",
    color: "bg-pink-700",
    category: "events",
    sortOrder: 42,
    averagePrice: "50.00",
    estimatedDuration: "4-8 hours",
    skillLevel: "intermediate"
  },
  {
    name: "Catering Services",
    nameAr: "خدمات التموين",
    nameFr: "Services de Restauration",
    description: "Food preparation and catering for events",
    descriptionAr: "إعداد الطعام والتموين للأحداث",
    descriptionFr: "Préparation de nourriture et restauration pour événements",
    icon: "ChefHat",
    color: "bg-orange-700",
    category: "events",
    sortOrder: 43,
    averagePrice: "40.00",
    estimatedDuration: "3-6 hours",
    skillLevel: "intermediate"
  },

  // 💄 BEAUTY & WELLNESS (7 categories)
  {
    name: "Hair Styling",
    nameAr: "تصفيف الشعر",
    nameFr: "Coiffure",
    description: "Professional hair cutting and styling",
    descriptionAr: "قص وتصفيف الشعر المهني",
    descriptionFr: "Coupe et coiffure professionnelles",
    icon: "Scissors",
    color: "bg-rose-600",
    category: "beauty",
    sortOrder: 44,
    averagePrice: "35.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "expert"
  },
  {
    name: "Massage Therapy",
    nameAr: "العلاج بالتدليك",
    nameFr: "Thérapie par Massage",
    description: "Therapeutic and relaxation massage services",
    descriptionAr: "خدمات التدليك العلاجي والاسترخاء",
    descriptionFr: "Services de massage thérapeutique et de relaxation",
    icon: "Hand",
    color: "bg-teal-700",
    category: "beauty",
    sortOrder: 45,
    averagePrice: "60.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "expert",
    requiresLicense: true
  },
  {
    name: "Makeup Services",
    nameAr: "خدمات المكياج",
    nameFr: "Services de Maquillage",
    description: "Professional makeup for events and photoshoots",
    descriptionAr: "المكياج المهني للأحداث وجلسات التصوير",
    descriptionFr: "Maquillage professionnel pour événements et séances photo",
    icon: "Sparkles",
    color: "bg-pink-800",
    category: "beauty",
    sortOrder: 46,
    averagePrice: "45.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "intermediate"
  },

  // 📸 CREATIVE SERVICES (8 categories)
  {
    name: "Photography",
    nameAr: "التصوير الفوتوغرافي",
    nameFr: "Photographie",
    description: "Event, portrait, and commercial photography",
    descriptionAr: "تصوير الأحداث والبورتريه والتصوير التجاري",
    descriptionFr: "Photographie d'événements, portraits et commerciale",
    icon: "Camera",
    color: "bg-gray-700",
    category: "creative",
    sortOrder: 47,
    averagePrice: "75.00",
    estimatedDuration: "2-6 hours",
    skillLevel: "expert"
  },
  {
    name: "Videography",
    nameAr: "التصوير المرئي",
    nameFr: "Vidéographie",
    description: "Video production and editing services",
    descriptionAr: "خدمات إنتاج وتحرير الفيديو",
    descriptionFr: "Services de production et montage vidéo",
    icon: "Video",
    color: "bg-red-800",
    category: "creative",
    sortOrder: 48,
    averagePrice: "80.00",
    estimatedDuration: "3-8 hours",
    skillLevel: "expert"
  },
  {
    name: "Graphic Design",
    nameAr: "التصميم الجرافيكي",
    nameFr: "Design Graphique",
    description: "Logo design, flyers, and marketing materials",
    descriptionAr: "تصميم الشعارات والنشرات والمواد التسويقية",
    descriptionFr: "Conception de logos, dépliants et matériel marketing",
    icon: "Palette",
    color: "bg-violet-700",
    category: "creative",
    sortOrder: 49,
    averagePrice: "40.00",
    estimatedDuration: "2-6 hours",
    skillLevel: "expert"
  },
  {
    name: "Music Lessons",
    nameAr: "دروس الموسيقى",
    nameFr: "Cours de Musique",
    description: "Private music instruction and lessons",
    descriptionAr: "التعليم الموسيقي الخاص والدروس",
    descriptionFr: "Instruction musicale privée et cours",
    icon: "Music",
    color: "bg-indigo-800",
    category: "creative",
    sortOrder: 50,
    averagePrice: "40.00",
    estimatedDuration: "1-2 hours",
    skillLevel: "expert"
  }
];

export async function seedServiceCategories() {
  try {
    console.log("Seeding service categories...");
    
    // Insert all categories
    await db.insert(serviceCategories).values(SERVICE_CATEGORIES);
    
    console.log(`Successfully seeded ${SERVICE_CATEGORIES.length} service categories`);
  } catch (error) {
    console.error("Error seeding service categories:", error);
    throw error;
  }
}