// Algeria's 58 Wilayas with both Latin and Arabic names
export const ALGERIA_WILAYAS = [
  { code: '01', latin: 'Adrar', arabic: 'أدرار' },
  { code: '02', latin: 'Chlef', arabic: 'الشلف' },
  { code: '03', latin: 'Laghouat', arabic: 'الأغواط' },
  { code: '04', latin: 'Oum El Bouaghi', arabic: 'أم البواقي' },
  { code: '05', latin: 'Batna', arabic: 'باتنة' },
  { code: '06', latin: 'Béjaïa', arabic: 'بجاية' },
  { code: '07', latin: 'Biskra', arabic: 'بسكرة' },
  { code: '08', latin: 'Béchar', arabic: 'بشار' },
  { code: '09', latin: 'Blida', arabic: 'البليدة' },
  { code: '10', latin: 'Bouira', arabic: 'البويرة' },
  { code: '11', latin: 'Tamanrasset', arabic: 'تمنراست' },
  { code: '12', latin: 'Tébessa', arabic: 'تبسة' },
  { code: '13', latin: 'Tlemcen', arabic: 'تلمسان' },
  { code: '14', latin: 'Tiaret', arabic: 'تيارت' },
  { code: '15', latin: 'Tizi Ouzou', arabic: 'تيزي وزو' },
  { code: '16', latin: 'Algiers', arabic: 'الجزائر' },
  { code: '17', latin: 'Djelfa', arabic: 'الجلفة' },
  { code: '18', latin: 'Jijel', arabic: 'جيجل' },
  { code: '19', latin: 'Sétif', arabic: 'سطيف' },
  { code: '20', latin: 'Saïda', arabic: 'سعيدة' },
  { code: '21', latin: 'Skikda', arabic: 'سكيكدة' },
  { code: '22', latin: 'Sidi Bel Abbès', arabic: 'سيدي بلعباس' },
  { code: '23', latin: 'Annaba', arabic: 'عنابة' },
  { code: '24', latin: 'Guelma', arabic: 'قالمة' },
  { code: '25', latin: 'Constantine', arabic: 'قسنطينة' },
  { code: '26', latin: 'Médéa', arabic: 'المدية' },
  { code: '27', latin: 'Mostaganem', arabic: 'مستغانم' },
  { code: '28', latin: 'M\'Sila', arabic: 'المسيلة' },
  { code: '29', latin: 'Mascara', arabic: 'معسكر' },
  { code: '30', latin: 'Ouargla', arabic: 'ورقلة' },
  { code: '31', latin: 'Oran', arabic: 'وهران' },
  { code: '32', latin: 'El Bayadh', arabic: 'البيض' },
  { code: '33', latin: 'Illizi', arabic: 'إليزي' },
  { code: '34', latin: 'Bordj Bou Arréridj', arabic: 'برج بوعريريج' },
  { code: '35', latin: 'Boumerdès', arabic: 'بومرداس' },
  { code: '36', latin: 'El Tarf', arabic: 'الطارف' },
  { code: '37', latin: 'Tindouf', arabic: 'تندوف' },
  { code: '38', latin: 'Tissemsilt', arabic: 'تيسمسيلت' },
  { code: '39', latin: 'El Oued', arabic: 'الوادي' },
  { code: '40', latin: 'Khenchela', arabic: 'خنشلة' },
  { code: '41', latin: 'Souk Ahras', arabic: 'سوق أهراس' },
  { code: '42', latin: 'Tipaza', arabic: 'تيبازة' },
  { code: '43', latin: 'Mila', arabic: 'ميلة' },
  { code: '44', latin: 'Aïn Defla', arabic: 'عين الدفلى' },
  { code: '45', latin: 'Naama', arabic: 'النعامة' },
  { code: '46', latin: 'Aïn Témouchent', arabic: 'عين تموشنت' },
  { code: '47', latin: 'Ghardaïa', arabic: 'غرداية' },
  { code: '48', latin: 'Relizane', arabic: 'غليزان' },
  { code: '49', latin: 'Timimoun', arabic: 'تيميمون' },
  { code: '50', latin: 'Bordj Badji Mokhtar', arabic: 'برج باجي مختار' },
  { code: '51', latin: 'Ouled Djellal', arabic: 'أولاد جلال' },
  { code: '52', latin: 'Béni Abbès', arabic: 'بني عباس' },
  { code: '53', latin: 'In Salah', arabic: 'عين صالح' },
  { code: '54', latin: 'In Guezzam', arabic: 'عين قزام' },
  { code: '55', latin: 'Touggourt', arabic: 'تقرت' },
  { code: '56', latin: 'Djanet', arabic: 'جانت' },
  { code: '57', latin: 'El M\'Ghair', arabic: 'المغير' },
  { code: '58', latin: 'El Meniaa', arabic: 'المنيعة' }
];

export type WilayaCode = typeof ALGERIA_WILAYAS[number]['code'];
export type Wilaya = typeof ALGERIA_WILAYAS[number];